include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_relative_imports: true
    always_use_package_imports: false
    always_put_required_named_parameters_first: false
